---
- name: Install s3fs
  become: yes
  command: apt install -yq s3fs

- name: Add read permission to other users
  become: yes
  file:
    path: /etc/fuse.conf
    state: file
    mode: "o=r"

- name: Allow non-root users to specify the allow_other or allow_root mount options
  become: yes
  lineinfile:
    dest: "/etc/fuse.conf"
    regexp: "^#user_allow_other$"
    line: "user_allow_other"
    state: present
    backrefs: yes
